version: '3.8'

services:
  app:
    container_name: shiftforward-io
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
